function out = func_ReadFiles(subj, ses, task_name, Dirs)

ffiles = dir(fullfile(subj.path, ses, 'func'));
ffiles = ffiles(3:end);
preprocDir = Dirs.out;
sfiles = dir(fullfile(preprocDir, subj.id, ses, 'anat'));
sfiles = sfiles(3:end);


fdata = ffiles(contains({ffiles.name}, subj.id) & ...
               contains({ffiles.name}, ses) & ...
               contains({ffiles.name}, ['task-' task_name]) & ...
               contains({ffiles.name}, 'bold.nii'));
           
sdata = sfiles(contains({sfiles.name}, subj.id) & ...
               contains({sfiles.name}, ses) & ...
               contains({sfiles.name}, 'run-fmri') & ...
               contains({sfiles.name}, 'T1w_bc.nii'));
           
if isempty(sdata) % if fMRI session T1 does not exist, use the DWI session T1
    sdata = sfiles(contains({sfiles.name}, subj.id) & ...
                   contains({sfiles.name}, ses) & ...
                   contains({sfiles.name}, 'run-dti') & ...
                   contains({sfiles.name}, 'T1w_bc.nii'));
end

out = {fullfile(subj.path, ses, 'func', fdata.name), ...
       fullfile(preprocDir, subj.id, ses, 'anat', sdata.name)};